name: epidemic-control-as-pomdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - matplotlib
  - seaborn
  - pytest
  - flake8
  - black
  - gymnasium
  - pandas
  - pip
  - pip:
    - stable-baselines3
    - tensorboard


